apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
  labels:
    app: data-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: busybox
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date): Сообщение от busybox" >> /shared/data.txt
            sleep 5
          done
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      - name: multitool
        image: wbitt/network-multitool
        command:
        - /bin/sh
        - -c
        - |
          tail -f /shared/data.txt
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
